### ISSUE TITLE
Lithnet package for dot net  core and dot net 6

### ISSUE THREAD

**Issue by PradeepGowda036** [lithnet/mms-utilities#1]
Hi there,

I came across the requirement to customize the Microsoft Identity Management where in I need to achieve the functionalities of the MIM in dot core / dot net6. Could any one tell me when the  **Lithnet.ResourceManagement.Client** package will be available for dot net core/ dot net 6

Thanks in advance

Regards, 
Pradeep

**Comment by ryannewington** [comment]
@PradeepGowda036 I've replied to your other ticket so i'll close this.
